# Generated by Django 5.0.4 on 2024-05-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0002_alter_filial_options_alter_membro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='membros',
            field=models.ManyToManyField(blank=True, to='reuniao.membro'),
        ),
    ]
