# Generated by Django 5.1 on 2024-08-11 20:47

import reuniao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0003_reuniao_membros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniao',
            options={'ordering': ['-hora_final'], 'verbose_name': 'Reunião', 'verbose_name_plural': 'Reuniões'},
        ),
        migrations.AddField(
            model_name='membro',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, validators=[reuniao.models.validar_cpf]),
        ),
        migrations.AlterUniqueTogether(
            name='filial',
            unique_together={('descricao',)},
        ),
        migrations.AlterUniqueTogether(
            name='membro',
            unique_together={('cpf',)},
        ),
    ]
