# Generated by Django 5.1 on 2024-08-11 18:17

import reuniao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0004_alter_reuniao_options_membro_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='celular',
            field=models.CharField(max_length=15, validators=[reuniao.models.formatar_telefone]),
        ),
    ]
